services:
  frontend:
    image: ghcr.io/oleg-blinov/safe-contact/frontend:latest
    container_name: sc-frontend
    restart: always
    networks:
      - internet

  backend:
    image: ghcr.io/oleg-blinov/safe-contact/backend:latest
    container_name: sc-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      # Настройки Logto
      - LOGTO_CLIENT_ID=tav5btfloqrfq3l6u7hsg
      - LOGTO_CLIENT_SECRET=Q4Ud5gKHzkNm3KUoAB8ZmdVgroT9pALS
      - LOGTO_ISSUER=https://3jocgf.logto.app/oidc
      - LOGTO_REDIRECT_URI=https://api.safe-contact.duckdns.org/auth/callback
      # Секретный ключ Flask (обязателен, замените на свой надёжный)
      - SECRET_KEY=4ae28ee12d16ee3be4b70b222bc3222d66fb0c68f24a144b91010015e40b01bc
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internet
      - internal

  db:
    image: postgres:15-alpine
    container_name: sc-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - sc_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    container_name: sc-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - internet
      - internal
    depends_on:
      - db

networks:
  internet:
    external: true
  internal:
    driver: bridge

volumes:
  sc_db_data: