services:
  frontend:
    image: ghcr.io/oleg-blinov/safe-contact/frontend:latest
    container_name: sc-frontend
    restart: always
    networks:
      - internet

  backend:
    image: ghcr.io/oleg-blinov/safe-contact/backend:latest
    container_name: sc-backend
    restart: always
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - LOGTO_CLIENT_ID=${LOGTO_CLIENT_ID}
      - LOGTO_CLIENT_SECRET=${LOGTO_CLIENT_SECRET}
      - LOGTO_ISSUER=${LOGTO_ISSUER}
      - LOGTO_REDIRECT_URI=${LOGTO_REDIRECT_URI}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internet
      - internal

  db:
    image: postgres:15-alpine
    container_name: sc-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - sc_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    container_name: sc-pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    networks:
      - internet
      - internal
    depends_on:
      - db

networks:
  internet:
    external: true
  internal:
    driver: bridge

volumes:
  sc_db_data: