---
- name: Server setup
  hosts: webserver
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install system dependencies
      apt:
        pkg:
          - docker.io
          - docker-compose-v2
          - python3-pip
          - python3-docker
        state: present

    - name: Ensure infra directory exists
      file:
        path: /opt/infra
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0755"

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Reset connection to apply group changes
      meta: reset_connection

    - name: Create 'internet' docker network
      docker_network:
        name: internet
        driver: bridge

    - name: Create Portainer volume
      docker_volume:
        name: portainer_data

    - name: Start Glances (System Monitor)
      docker_container:
        name: glances
        image: nicolargo/glances:latest
        restart_policy: always
        pid_mode: host
        networks:
          - name: internet
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock:ro
        command: /usr/local/bin/glances -w

    - name: Start Portainer (Docker Management)
      docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        restart_policy: always
        networks:
          - name: internet
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

    - name: Start Nginx Proxy Manager
      docker_container:
        name: nginx-proxy-manager
        image: "jc21/nginx-proxy-manager:latest"
        restart_policy: always
        ports:
          - "80:80"
          - "81:81"
          - "443:443"
        networks:
          - name: internet
        volumes:
          - /opt/npm/data:/data
          - /opt/npm/letsencrypt:/etc/letsencrypt
