"""empty message

Revision ID: 1410c85d5e1f
Revises: a3057ca82341
Create Date: 2026-05-01 14:28:25.251781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1410c85d5e1f'
down_revision = 'a3057ca82341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active_role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('last_active_role')

    # ### end Alembic commands ###
