"""empty message

Revision ID: 16f0a9238115
Revises: 85370a2c06b3
Create Date: 2026-04-19 10:48:31.537948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f0a9238115'
down_revision = '85370a2c06b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('origin_name', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.drop_column('origin_name')
        batch_op.drop_column('verification_status')

    # ### end Alembic commands ###
