"""empty message

Revision ID: 24107b7da08c
Revises: 1410c85d5e1f
Create Date: 2026-05-02 14:00:33.071802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24107b7da08c'
down_revision = '1410c85d5e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointment_client_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('appointment_slot_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'slot', ['slot_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('consent_type_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'consent_type', ['type_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'member', ['verified_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('member_consent', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('member_consent_consent_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('member_consent_member_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'consent', ['consent_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('member_role', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('member_role_member_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('member_role_role_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'role', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('review_specialist_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_client_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_appointment_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'client', ['client_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'appointment', ['appointment_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.alter_column('education',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('specialist_member_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('specialist_issue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('specialist_issue_issue_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'issue', ['issue_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('specialist_method', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('specialist_method_method_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'method', ['method_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('specialistdocument_specialist_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specialistdocument_specialist_id_fkey'), 'specialist', ['specialist_id'], ['id'])

    with op.batch_alter_table('specialist_method', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specialist_method_method_id_fkey'), 'method', ['method_id'], ['id'])

    with op.batch_alter_table('specialist_issue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specialist_issue_issue_id_fkey'), 'issue', ['issue_id'], ['id'])

    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specialist_member_id_fkey'), 'member', ['member_id'], ['id'])
        batch_op.alter_column('education',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_appointment_id_fkey'), 'appointment', ['appointment_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('review_client_id_fkey'), 'client', ['client_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('review_specialist_id_fkey'), 'specialist', ['specialist_id'], ['id'])

    with op.batch_alter_table('member_role', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('member_role_role_id_fkey'), 'role', ['role_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('member_role_member_id_fkey'), 'member', ['member_id'], ['id'])

    with op.batch_alter_table('member_consent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('member_consent_member_id_fkey'), 'member', ['member_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('member_consent_consent_id_fkey'), 'consent', ['consent_id'], ['id'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('verified_by')

    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consent_type_id_fkey'), 'consent_type', ['type_id'], ['id'])

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointment_slot_id_fkey'), 'slot', ['slot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('appointment_client_id_fkey'), 'client', ['client_id'], ['id'])

    # ### end Alembic commands ###
