"""empty message

Revision ID: 2ca5819b82a1
Revises: 3bb89a5d3ae5
Create Date: 2026-04-19 14:15:43.304380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca5819b82a1'
down_revision = '3bb89a5d3ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.alter_column('base_price',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.alter_column('base_price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
