"""empty message

Revision ID: 3292f51f553d
Revises: 648fad911886
Create Date: 2026-04-18 07:54:17.190552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3292f51f553d'
down_revision = '648fad911886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), server_default='1500', nullable=False))

    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_visible')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('is_approved')
        batch_op.drop_column('verification_status')

    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
