"""empty message

Revision ID: 6ac005bd79a2
Revises: 5056c67749b3
Create Date: 2026-04-11 18:13:19.356459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac005bd79a2'
down_revision = '5056c67749b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('slot_specialist_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('specialist_issue', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('specialist_issue_specialist_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('specialist_method', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('specialist_method_specialist_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialist', ['specialist_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist_method', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specialist_method_specialist_id_fkey'), 'specialist', ['specialist_id'], ['id'])

    with op.batch_alter_table('specialist_issue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('specialist_issue_specialist_id_fkey'), 'specialist', ['specialist_id'], ['id'])

    with op.batch_alter_table('slot', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('slot_specialist_id_fkey'), 'specialist', ['specialist_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
