"""empty message

Revision ID: 6ff84e8589b1
Revises: 3292f51f553d
Create Date: 2026-04-18 08:51:23.302221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ff84e8589b1'
down_revision = '3292f51f553d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), server_default='1500', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
