"""empty message

Revision ID: 85370a2c06b3
Revises: 6ff84e8589b1
Create Date: 2026-04-18 09:39:37.537398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85370a2c06b3'
down_revision = '6ff84e8589b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specialistdocument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verified_by', sa.Integer(), nullable=True),
    sa.Column('specialist_id', sa.Integer(), nullable=True),
    sa.Column('document_title', sa.String(length=32), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('uploaded_time', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['specialist_id'], ['specialist.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.alter_column('base_price',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialist', schema=None) as batch_op:
        batch_op.alter_column('base_price',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('specialistdocument')
    # ### end Alembic commands ###
