"""empty message

Revision ID: 9294cce049d5
Revises: 6c9ffff872c5
Create Date: 2026-04-19 11:06:44.609898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9294cce049d5'
down_revision = '6c9ffff872c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.alter_column('file_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('origin_name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.alter_column('origin_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=32),
               existing_nullable=True)
        batch_op.alter_column('file_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
