"""empty message

Revision ID: b7eb860d26ed
Revises: b8af91d6a77a
Create Date: 2026-04-30 17:39:11.088885

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b7eb860d26ed"
down_revision = "b8af91d6a77a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specialist", schema=None) as batch_op:
        batch_op.alter_column(
            "education",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("specialist", schema=None) as batch_op:
        batch_op.alter_column(
            "education",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=True,
        )
    # ### end Alembic commands ###
