"""empty message

Revision ID: c2a404fe982a
Revises: 9294cce049d5
Create Date: 2026-04-19 11:09:12.831127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a404fe982a'
down_revision = '9294cce049d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.alter_column('reject_reason',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.alter_column('reject_reason',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
