"""empty message

Revision ID: f7749df23dc2
Revises: 16f0a9238115
Create Date: 2026-04-19 10:50:56.005616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7749df23dc2'
down_revision = '16f0a9238115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reject_reason', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specialistdocument', schema=None) as batch_op:
        batch_op.drop_column('reject_reason')

    # ### end Alembic commands ###
